version: 2

seeds:
  - name: patients
    description: "Synthetic NHS patient master."
    columns:
      - name: patient_id
        tests: [not_null, unique]
      - name: nhs_number
        description: "10-digit NHS number; may contain spaces in raw."
        tests: [not_null]
      - name: first_name
        tests: [not_null]
      - name: last_name
        tests: [not_null]
      - name: dob
        description: "Date of birth (YYYY-MM-DD)."
        tests: [not_null]
      - name: gender
        tests:
          - not_null
          - accepted_values:
              values: ['Male', 'Female', 'Other']
      - name: postcode
        tests: [not_null]
      - name: ethnicity
        tests:
          - not_null
          - accepted_values:
              values:
                ['White British','Black African','Black Caribbean','South Asian','East Asian','Mixed','Other']
      - name: risk_level
        tests:
          - accepted_values:
              values: ['Low', 'Medium', 'High']

  - name: gp
    description: "Raw GP practice registry."
    columns:
      - name: gp_id
        tests: [not_null, unique]
      - name: name
        tests: [not_null]
      - name: practice
        tests: [not_null]
      - name: postcode
        tests: [not_null]

  - name: trusts
    description: "Raw NHS Trust registry."
    columns:
      - name: trust_id
        tests: [not_null, unique]
      - name: name
        tests: [not_null]
      - name: region
        tests: [not_null]

  - name: referrals
    description: "Raw referrals from GPs to Trusts."
    columns:
      - name: referral_id
        tests: [not_null, unique]
      - name: patient_id
        tests:
          - not_null
          - relationships: {to: ref('patients'), field: patient_id}
      - name: gp_id
        tests:
          - not_null
          - relationships: {to: ref('gp'), field: gp_id}
      - name: referral_date
        tests: [not_null]
      - name: specialty
        tests:
          - not_null
          - accepted_values:
              values:
                ['Cardiology','General Surgery','Endocrinology','Dermatology','Gastroenterology','Neurology','Oncology','Orthopaedics','Paediatrics','Psychiatry','Urology','Rheumatology','Respiratory Medicine']
      - name: reason
        tests: [not_null]
      - name: referral_status
        tests:
          - not_null
          - accepted_values:
              values: ['Pending','Accepted','Rejected','Completed','Open','Closed']
      - name: trust_id
        tests:
          - not_null
          - relationships: {to: ref('trusts'), field: trust_id}
      - name: notes

  - name: appointments
    description: "Raw elective care appointments."
    columns:
      - name: appointment_id
        tests: [not_null, unique]
      - name: patient_id
        tests:
          - not_null
          - relationships: {to: ref('patients'), field: patient_id}
      - name: trust_id
        tests:
          - not_null
          - relationships: {to: ref('trusts'), field: trust_id}
      - name: specialty
        tests:
          - not_null
          - accepted_values:
              values:
                ['Cardiology','General Surgery','Endocrinology','Dermatology','Gastroenterology','Neurology','Oncology','Orthopaedics','Paediatrics','Psychiatry','Urology','Rheumatology','Respiratory Medicine']
      - name: appt_date
        tests: [not_null]
      - name: appt_status
        tests:
          - not_null
          - accepted_values:
              values: ['Scheduled','Completed','Cancelled','No Show','Rescheduled','Overdue']
      - name: referral_date
        tests: [not_null]
      - name: wait_weeks
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true

  - name: conditions
    description: "Raw patient conditions/comorbidities."
    columns:
      - name: condition_id
        tests: [not_null, unique]
      - name: patient_id
        tests:
          - not_null
          - relationships: {to: ref('patients'), field: patient_id}
      - name: condition_name
        tests: [not_null]
      - name: severity
        tests:
          - not_null
          - accepted_values:
              values: ['Mild','Moderate','Severe','Critical']
      - name: active
        tests:
          - not_null
          - accepted_values:
              values: ['Yes','No']

  - name: procedures
    description: "Raw elective procedures."
    columns:
      - name: procedure_id
        tests: [not_null, unique]
      - name: patient_id
        tests:
          - not_null
          - relationships: {to: ref('patients'), field: patient_id}
      - name: procedure_name
        tests: [not_null]
      - name: planned_date
        tests: [not_null]
      - name: actual_date
      - name: status
        tests:
          - not_null
          - accepted_values:
              values: ['Scheduled','Completed','Cancelled','Postponed','Planned','Delayed']

  - name: sla_by_specialty
    description: "Raw RTT SLA thresholds by specialty."
    columns:
      - name: specialty
        tests:
          - not_null
          - unique
          - accepted_values:
              values:
                ['Cardiology','Urology','Neurology','General Surgery','Dermatology','Endocrinology','Orthopaedics','Gastroenterology','Respiratory Medicine','Rheumatology']
      - name: rtt_weeks_threshold
        tests: [not_null]

models:
  # --- staging ---
  - name: stg_patients
    description: "Cleaned patient master data."
    columns:
      - name: patient_sk
        tests: [not_null, unique]
      - name: patient_id
        tests: [not_null, unique]
      - name: nhs_number
        tests: [not_null, unique, nhs_number_valid]
      - name: dob
        tests: [not_null]
      - name: gender
        tests:
          - accepted_values: { values: ['Male','Female','Other'] }
      - name: postcode
        tests: [not_null]
      - name: ethnicity
        tests:
          - not_null
          - accepted_values: { values: ['White British','Black African','Black Caribbean','South Asian','East Asian','Mixed','Other'] }
      - name: risk_level
        tests:
          - accepted_values: { values: ['Low','Medium','High'] }

  - name: stg_gp
    description: "GP practice registry."
    columns:
      - name: gp_sk
        tests: [not_null, unique]
      - name: gp_id
        tests: [not_null, unique]
      - name: gp_name
        tests: [not_null]
      - name: practice
        tests: [not_null]
      - name: postcode
        tests: [not_null]

  - name: stg_trusts
    description: "NHS Trust registry."
    columns:
      - name: trust_sk
        tests: [not_null, unique]
      - name: trust_id
        tests: [not_null, unique]
      - name: trust_name
        tests: [not_null]
      - name: region
        tests: [not_null]

  - name: stg_referrals
    description: "Referrals from GPs to Trusts."
    columns:
      - name: referral_sk
        tests: [not_null, unique]
      - name: referral_id
        tests: [not_null, unique]
      - name: patient_id
        tests:
          - not_null
          - relationships: {to: ref('stg_patients'), field: patient_id}
      - name: gp_id
        tests:
          - not_null
          - relationships: {to: ref('stg_gp'), field: gp_id}
      - name: referral_date
        tests: [not_null]
      - name: specialty
        tests:
          - not_null
          - accepted_values: { values: ['Cardiology','General Surgery','Endocrinology','Dermatology','Gastroenterology','Neurology','Oncology','Orthopaedics','Paediatrics','Psychiatry','Urology','Rheumatology','Respiratory Medicine'] }
      - name: reason
        tests: [not_null]
      - name: referral_status
        tests:
          - accepted_values: { values: ['Pending','Accepted','Rejected','Completed','Open','Closed'] }
      - name: trust_id
        tests:
          - not_null
          - relationships: {to: ref('stg_trusts'), field: trust_id}
      - name: notes

  - name: stg_appointments
    description: "Elective care appointments."
    columns:
      - name: appointment_sk
        tests: [not_null, unique]
      - name: appointment_id
        tests: [not_null, unique]
      - name: patient_id
        tests:
          - not_null
          - relationships: {to: ref('stg_patients'), field: patient_id}
      - name: trust_id
        tests:
          - not_null
          - relationships: {to: ref('stg_trusts'), field: trust_id}
      - name: specialty
        tests: [not_null]
      - name: appointment_date
        tests: [not_null]
      - name: appointment_status
        tests:
          - accepted_values: { values: ['SCHEDULED','COMPLETED','CANCELLED','NO SHOW','RESCHEDULED','OVERDUE'] }
      - name: referral_date
        tests: [not_null]
      - name: wait_weeks
        tests:
          - dbt_utils.accepted_range: { min_value: 0, inclusive: true }

  - name: stg_procedures
    description: "Elective procedures."
    columns:
      - name: procedure_sk
        tests: [not_null, unique]
      - name: procedure_id
        tests: [not_null, unique]
      - name: patient_id
        tests:
          - not_null
          - relationships: {to: ref('stg_patients'), field: patient_id}
      - name: procedure_name
        tests: [not_null]
      - name: planned_date
        tests: [not_null]
      - name: actual_date
      - name: procedure_status
        tests:
          - accepted_values: { values: ['Scheduled','Completed','Cancelled','Postponed','Planned','Delayed'] }

  - name: stg_conditions
    description: "Patient conditions/comorbidities."
    columns:
      - name: condition_sk
        tests: [not_null, unique]
      - name: condition_id
        tests: [not_null, unique]
      - name: patient_id
        tests:
          - not_null
          - relationships: {to: ref('stg_patients'), field: patient_id}
      - name: condition_name
        tests: [not_null]
      - name: severity
        tests:
          - accepted_values: { values: ['Mild','Moderate','Severe','Critical'] }
      - name: active
        tests:
          - accepted_values: { values: ['Yes','No'] }

  - name: stg_sla_by_specialty
    description: "SLA by specialty (RTT weeks)."
    columns:
      - name: sla_sk
        tests: [not_null, unique]
      - name: specialty
        tests: [not_null, unique]
      - name: rtt_weeks_threshold
        tests: [not_null]
      - name: verification_needed
        tests: [not_null]

  # --- intermediate models ---
  - name: int_appointment_enriched
    description: "Appointments matched with latest referral and wait time."
    columns:
      - name: appointment_id
        tests: [not_null, unique]
      - name: patient_id
        tests: [not_null]
      - name: referral_id
        tests:
          - relationships:
              to: ref('stg_referrals')
              field: referral_id
              config: { severity: warn }
      - name: wait_weeks
        tests:
          - dbt_utils.accepted_range: { min_value: 0, inclusive: true }

  - name: int_procedure_enriched
    description: "Procedures enriched with referral linkage and RTT metrics."
    columns:
      - name: procedure_id
        tests: [not_null, unique]
      - name: patient_id
        tests: [not_null]
      - name: referral_id
        tests:
          - relationships:
              to: ref('stg_referrals')
              field: referral_id
              config: { severity: warn }
      - name: procedure_wait_days
      - name: rtt_weeks
        tests:
          - dbt_utils.accepted_range: { min_value: 0, inclusive: true }

  - name: int_referral_enriched
    description: "Referrals with first appointment metrics."
    columns:
      - name: referral_id
        tests: [not_null, unique]
      - name: patient_id
        tests: [not_null]
      - name: first_appointment_date
      - name: weeks_to_first_appointment
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
              config: { severity: warn }

  - name: int_capacity_weekly
    description: "Weekly appointment slots and capacity metrics."
    columns:
      - name: trust_id
        tests: [not_null]
      - name: specialty
        tests: [not_null]
      - name: week_start
        tests:
          - not_null
          - unique:
              combination_of_columns: [trust_id, specialty, week_start]
      - name: total_slots
      - name: planned_slots
        tests:
          - dbt_utils.expression_is_true:
              expression: "planned_slots <= total_slots"
      - name: attended_slots
      - name: cancelled_slots
      - name: dna_slots

  - name: int_patient_features
    description: "Patient-level enriched features (age, comorbidities, attendance)."
    columns:
      - name: patient_sk
        tests: [not_null, unique]
      - name: patient_id
        tests: [not_null]
      - name: comorbidity_count
        tests:
          - dbt_utils.accepted_range: { min_value: 0, inclusive: true }
      - name: cancellations_lifetime
        tests:
          - dbt_utils.accepted_range: { min_value: 0, inclusive: true }
      - name: dna_lifetime
        tests:
          - dbt_utils.accepted_range: { min_value: 0, inclusive: true }
      - name: age_years
        tests:
          - dbt_utils.accepted_range: { min_value: 0, inclusive: true }

  # - name: int_patient_waitlist_spine
  #   description: "Daily spine of open waitlist states per patient × specialty × trust."
  #   columns:
  #     - name: composite_key
  #       tests: [not_null, unique]
  #     - name: patient_id
  #       tests: [not_null]
  #     - name: specialty
  #       tests: [not_null]
  #     - name: trust_id
  #       tests: [not_null]
  #     - name: snapshot_date
  #       tests: [not_null]
  #     - name: is_open_wait
  #       tests:
  #         - dbt_utils.accepted_range: { min_value: 0, max_value: 1, inclusive: true }
# -- PARKED MODEL: patient_waitlist_spine
# -- Reason: too complex for v1, revisit in v2 with hybrid Python/SQL solution
